### ISSUE TITLE
Razer Tartarus Chroma V2

### ISSUE THREAD

**Issue by waytoomuchgaming** [thatguystone/lintartarus#3]
Hello

Will your software work with the newer version of the Tartarus, the v2 ?
If yes, i'll gladly use a Debian package (or Ubuntu PPA), as i fear i won't be tech-savvy enough to use the command line.

**Comment by thatguystone** [comment]
I doubt it's going to work. I [hardcoded it for my product id](https://github.com/thatguystone/lintartarus/blob/aec672f1d00338d9249d16b6c6bf7ca6ed54b630/src/const.h#L26), so unless yours has the same one, you're going to have to tweak it.

**Comment by waytoomuchgaming** [comment]
```
b@ordineuf:~$ lsusb | grep Razer
Bus 001 Device 002: ID 1532:0208 Razer USA, Ltd 
```

Seem very close. But i suppose if the ID is not the same, then a lot of other things can have changed too.
Oh well, ty anyway :)

**Comment by waytoomuchgaming** [comment]
I tried it anyway ^^
I just changed the ID in const.h , and then followed the readme instructions.
Then i do sudo ./lintartarus to launch it (i suppose that's what i'm supposed to do), and it put the lights off. So far, something happening :)
But that was the end of the joy. No key do anything (i tried them all with xev, they all seem disabled).
I tried to launch a program after having made a custom .ini file (which i put in ~/config/lintartarus/ and also in keymaps, because i was not sure), but nothing happen.
So... i suppose there is more things to change than just the ID.
Oh well, i tried ^^

**Comment by thatguystone** [comment]
It's been a while since I've looked at this, but the general flow for input is:

1. A synthetic keyboard device is created with`/dev/uinput`
1. `uinput.c` has a watch on `/dev/input/*`
1. The device is registered as a keyboard under `/dev/input/<device-ident>`
1. `uinput.c` grabs control of the device using `ioctl(EVIOCGRAB)` [0]
1. `uinput.c` then handles translating key events from the device into whatever keys were setup in the config file and feeding them back through the keyboard created above.

That should still work as long as the device is registering itself as a keyboard.

The USB part is only for controlling lights and such, and can probably be safely disabled for testing (and the protocol has probably changed for your new device).

I would try plugging the device in without lintartarus running, then see if a keyboard shows up in /dev/input and if xev recognizes key inputs then. If it's not showing up, then there's a good chance that the entire device has changed and would need a bunch of new work.

[0] https://github.com/thatguystone/lintartarus/blob/master/src/uinput.c#L190

**Comment by waytoomuchgaming** [comment]
Thank you for your answer, but i don't understand 10% of it, i'm just a user ^^

I unplugged and plugged the device, tho, and i see a bunch of "event*" files disappearing an appearing again in /dev/input. Also in /dev/input/by-id/, with more explicit names.

Xev recognize the keys input from the Tartarus, it's what i used to verify my attempt at using xkbcomp (who failed: i was able to remap exactly as i want the Tartarus, but each time i press a modifier - shift, ctrl, alt - and any key of the Tartarus, that key unmap itself, and become "stuck" in it's unmapped state, until i press the physical unmapped key somewhere else - usually on my regular keyboard).
